#!/bin/bash
	
echo "Creating venv"
py -3 -m venv venv
echo "Activating venv"
. venv/Scripts/activate
echo "Installing dependencies"
pip3 install -r requirements.txt
echo "All done. Now run ./runapp"

exit 0

